typedef unsigned int * GPPOINTER;

#define PERIPH_BASE 		((unsigned int)0x40000000) 		//0x4000 0000 external divice base address
#define APB2PERIPH_BASE 	(PERIPH_BASE+0x00010000) 		//0x4001 0000 apb2 bus base address
#define GPIOC_BASE 			(APB2PERIPH_BASE+0x1000) 		//0x4001 1000 gpioc base address
#define GPIOC_CRL			(GPPOINTER)(GPIOC_BASE+0x00)		//32bit=4byte
#define GPIOC_CRH			(GPPOINTER)(GPIOC_BASE+0x04)
#define GPIOC_IDR			(GPPOINTER)(GPIOC_BASE+0x08)
#define GPIOC_ODR			(GPPOINTER)(GPIOC_BASE+0x0c)
#define GPIOC_BSRR		(GPPOINTER)(GPIOC_BASE+0x10)
#define GPIOC_BRR			(GPPOINTER)(GPIOC_BASE+0x14)
#define GPIOC_LCKR		(GPPOINTER)(GPIOC_BASE+0x18)
#define AHBPERIPH_BASE		(PERIPH_BASE+0x00020000)		//open gpio clock,clock base address
#define RCC_BASE			(AHBPERIPH_BASE+0x1000)		//rcc is sys clock
#define RCC_APB2ENR			(GPPOINTER)(RCC_BASE+0x18)		//apb2 clock

#define GPIOA_BASE 			(APB2PERIPH_BASE+0x0800) 		//0x4001 0800
#define GPIOA_CRL			(GPPOINTER)(GPIOA_BASE+0x00)
#define GPIOA_CRH			(GPPOINTER)(GPIOA_BASE+0x04)
#define GPIOA_IDR			(GPPOINTER)(GPIOA_BASE+0x08)
#define GPIOA_ODR			(GPPOINTER)(GPIOA_BASE+0x0c)
#define GPIOA_BSRR		(GPPOINTER)(GPIOA_BASE+0x10)
#define GPIOA_BRR			(GPPOINTER)(GPIOA_BASE+0x14)
#define GPIOA_LCKR		(GPPOINTER)(GPIOA_BASE+0x18)

#define GPIOB_BASE 			(APB2PERIPH_BASE+0x0c00) 		//0x4001 0c00
#define GPIOB_CRL			(GPPOINTER)(GPIOB_BASE+0x00)
#define GPIOB_CRH			(GPPOINTER)(GPIOB_BASE+0x04)
#define GPIOB_IDR			(GPPOINTER)(GPIOB_BASE+0x08)
#define GPIOB_ODR			(GPPOINTER)(GPIOB_BASE+0x0c)
#define GPIOB_BSRR		(GPPOINTER)(GPIOB_BASE+0x10)
#define GPIOB_BRR			(GPPOINTER)(GPIOB_BASE+0x14)
#define GPIOB_LCKR		(GPPOINTER)(GPIOB_BASE+0x18)

#define GPIOD_BASE 			(APB2PERIPH_BASE+0x1400) 		//0x4001 1400
#define GPIOD_CRL			(GPPOINTER)(GPIOD_BASE+0x00)
#define GPIOD_CRH			(GPPOINTER)(GPIOD_BASE+0x04)
#define GPIOD_IDR			(GPPOINTER)(GPIOD_BASE+0x08)
#define GPIOD_ODR			(GPPOINTER)(GPIOD_BASE+0x0c)
#define GPIOD_BSRR		(GPPOINTER)(GPIOD_BASE+0x10)
#define GPIOD_BRR			(GPPOINTER)(GPIOD_BASE+0x14)
#define GPIOD_LCKR		(GPPOINTER)(GPIOD_BASE+0x18)

#define GPIOE_BASE 			(APB2PERIPH_BASE+0x1800) 		//0x4001 1800
#define GPIOE_CRL			(GPPOINTER)(GPIOE_BASE+0x00)
#define GPIOE_CRH			(GPPOINTER)(GPIOE_BASE+0x04)
#define GPIOE_IDR			(GPPOINTER)(GPIOE_BASE+0x08)
#define GPIOE_ODR			(GPPOINTER)(GPIOE_BASE+0x0c)
#define GPIOE_BSRR		(GPPOINTER)(GPIOE_BASE+0x10)
#define GPIOE_BRR			(GPPOINTER)(GPIOE_BASE+0x14)
#define GPIOE_LCKR		(GPPOINTER)(GPIOE_BASE+0x18)

#define GPIOF_BASE 			(APB2PERIPH_BASE+0x1c00) 		//0x4001 1c00
#define GPIOF_CRL			(GPPOINTER)(GPIOF_BASE+0x00)
#define GPIOF_CRH			(GPPOINTER)(GPIOF_BASE+0x04)
#define GPIOF_IDR			(GPPOINTER)(GPIOF_BASE+0x08)
#define GPIOF_ODR			(GPPOINTER)(GPIOF_BASE+0x0c)
#define GPIOF_BSRR		(GPPOINTER)(GPIOF_BASE+0x10)
#define GPIOF_BRR			(GPPOINTER)(GPIOF_BASE+0x14)
#define GPIOF_LCKR		(GPPOINTER)(GPIOF_BASE+0x18)

#define GPIOG_BASE 			(APB2PERIPH_BASE+0x2000) 		//0x4001 2000
#define GPIOG_CRL			(GPPOINTER)(GPIOG_BASE+0x00)
#define GPIOG_CRH			(GPPOINTER)(GPIOG_BASE+0x04)
#define GPIOG_IDR			(GPPOINTER)(GPIOG_BASE+0x08)
#define GPIOG_ODR			(GPPOINTER)(GPIOG_BASE+0x0c)
#define GPIOG_BSRR		(GPPOINTER)(GPIOG_BASE+0x10)
#define GPIOG_BRR			(GPPOINTER)(GPIOG_BASE+0x14)
#define GPIOG_LCKR		(GPPOINTER)(GPIOG_BASE+0x18)

