//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ComputerGraphics.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MYTYPE                      129
#define IDD_DLG_COLOR                   130
#define IDD_DLG_SIZE                    131
#define IDD_DLG_INPUTBOX                132
#define IDD_DLG_GVARY                   133
#define IDD_DLG_METERIAL                134
#define IDD_DLG_LIGHT                   135
#define IDD_DLG_GEOMODCREATE            136
#define IDD_DLG_OPERATIONTIPS           137
#define IDD_DLG_CARTONSETTING           138
#define IDD_DLG_BASEOPE                 139
#define IDC_SLIDER_RED                  1000
#define IDC_SLIDER_GREEN                1001
#define IDC_SLIDER_BLUE                 1002
#define IDC_STATIC_RED                  1003
#define IDC_STATIC_GREEN                1004
#define IDC_STATIC_BLUE                 1005
#define IDC_SLIDER_SIZE                 1006
#define IDC_STATIC_SIZE                 1007
#define IDC_EDIT_INPUT                  1008
#define IDC_STATIC_TIPS                 1009
#define IDC_STATIC_PROJANGLE            1010
#define IDC_STATIC_PROJAANGLE           1011
#define IDC_EDIT_PROJAANGLE             1012
#define IDC_EDIT_PROJBANGLE             1013
#define IDC_STATIC_PROJBANGLE           1014
#define IDC_STATIC_VIEWR                1015
#define IDC_EDIT_VIEWR                  1016
#define IDC_STATIC_VIEWD                1017
#define IDC_EDIT_VIEWD                  1018
#define IDC_STATIC_VIEW                 1019
#define IDC_STATIC_VIEWNEAR             1020
#define IDC_EDIT_VIEWRNEAR              1021
#define IDC_STATIC_VIEWDFAR             1022
#define IDC_EDIT_VIEWDFAR               1023
#define IDC_STATIC_FNFLAT               1024
#define IDC_STATIC_GMOVEX               1025
#define IDC_EDIT_GMOVEX                 1026
#define IDC_STATIC_GMOVEY               1027
#define IDC_EDIT_GMOVEY                 1028
#define IDC_STATIC_GMOVE                1029
#define IDC_STATIC_GMOVEZ               1030
#define IDC_EDIT_GMOVEZ                 1031
#define IDC_STATIC_GSCALEX              1032
#define IDC_EDIT_GSCALEX                1033
#define IDC_STATIC_GSCALEY              1034
#define IDC_EDIT_GSCALEY                1035
#define IDC_STATIC_GSCALE               1036
#define IDC_STATIC_GSCALEZ              1037
#define IDC_EDIT_GSCALEZ                1038
#define IDC_STATIC_GSPINX               1039
#define IDC_EDIT_GSPINX                 1040
#define IDC_STATIC_GSPINY               1041
#define IDC_EDIT_GSPINY                 1042
#define IDC_STATIC_GSPIN                1043
#define IDC_STATIC_GSPINZ               1044
#define IDC_EDIT_GSPINZ                 1045
#define IDC_CHECK_GREFLACTX             1046
#define IDC_CHECK_GREFLACTY             1047
#define IDC_CHECK_GREFLACTZ             1048
#define IDC_STATIC_GREFLACE             1049
#define IDC_CHECK_GFLATREFXOY           1050
#define IDC_CHECK_GFLATREFYOZ           1051
#define IDC_CHECK_GFLATREFXOZ           1052
#define IDC_STATIC_GFLATREF             1053
#define IDC_STATIC_GMISCUT              1054
#define IDC_EDIT_GMISCUTXGZ             1055
#define IDC_EDIT_GMISCUTXDY             1056
#define IDC_EDIT_GMISCUTYHZ             1057
#define IDC_EDIT_GMISCUTYBX             1058
#define IDC_EDIT_GMISCUTZFY             1059
#define IDC_EDIT_GMISCUTZCX             1060
#define IDC_STATIC_GMISCUTXGZ           1061
#define IDC_STATIC_GMISCUTXDY           1062
#define IDC_STATIC_GMISCUTYHZ           1063
#define IDC_STATIC_GMISCUTYBX           1064
#define IDC_STATIC_GMISCUTZFY           1065
#define IDC_STATIC_GMISCUTZCX           1066
#define IDC_CHECK_MOVE                  1067
#define IDC_CHECK_SPIN                  1068
#define IDC_CHECK_SCALE                 1069
#define IDC_CHECK_FALTREF               1070
#define IDC_CHECK_REFLACT               1071
#define IDC_CHECK_MISCUT                1072
#define IDC_CHECK_GOLD                  1097
#define IDC_CHECK_SIVER                 1098
#define IDC_CHECK_REDSTONE              1099
#define IDC_CHECK_GREENSTONE            1100
#define IDC_CHECK_SIVIR                 1102
#define IDC_EDIT_PX                     1105
#define IDC_EDIT_PY                     1106
#define IDC_EDIT_PZ                     1107
#define IDC_EDIT_CZERO                  1108
#define IDC_EDIT_CONE                   1109
#define IDC_EDIT_CTWO                   1110
#define IDC_STATIC_GCOLOR               1111
#define IDC_STATIC_GSUBFACTOR           1112
#define IDC_STATIC_CZERO                1113
#define IDC_STATIC_CONE                 1114
#define IDC_STATIC_CTWO                 1115
#define IDC_STATIC_GPOINT               1116
#define IDC_STATIC_PX                   1117
#define IDC_STATIC_PY                   1118
#define IDC_STATIC_PZ                   1119
#define IDC_STATIC_CTR_A                1120
#define IDC_EDIT_A                      1121
#define IDC_STATIC_CTR_R                1122
#define IDC_EDIT_R                      1123
#define IDC_STATIC_CTR_H                1124
#define IDC_EDIT_H                      1125
#define IDC_STATIC_CTR_RCOUNT           1126
#define IDC_EDIT_RCOUNT                 1127
#define IDC_STATIC_CTR_HCOUNT           1128
#define IDC_EDIT_HCOUNT                 1129
#define IDC_STATIC_CTR_RANGLECOUNT      1130
#define IDC_EDIT_RANGLECOUNT            1131
#define IDC_EDIT_AANGLECOUNT            1133
#define IDC_EDIT_BANGLECOUNT            1134
#define IDC_STATIC_CTR_ABANGLECOUNT     1135
#define IDC_STATIC_CTR_RTWO             1136
#define IDC_EDIT_RTWO                   1137
#define IDC_CHECK_OPENCARTON            1138
#define IDC_CHECK_SPINX                 1139
#define IDC_CHECK_SPINY                 1140
#define IDC_CHECK_SPINZ                 1141
#define IDC_EDIT_SPINX                  1142
#define IDC_EDIT_SPINY                  1143
#define IDC_EDIT_SPINZ                  1144
#define IDC_EDIT_UPDATETIME             1145
#define IDC_EDIT_BEZIER_TCOUNT          1146
#define IDC_EDIT_BEZIER_RANGLECOUNT     1147
#define IDC_STATIC_BEZIER_TCOUNT        1148
#define IDC_STATIC_BEZIER_RANGLE        1149
#define IDC_STATIC_BEZIER_SPINSETTING   1150
#define IDC_STATIC_GEOMOD_BALLEXLEVEL   1152
#define IDC_EDIT_BALLEX_LEVEL           1153
#define ID_PEN_COLOR                    32772
#define ID_PEN_SIZE                     32774
#define ID_BRUSH_COLOR                  32775
#define ID_DRAW_POINT                   32776
#define ID_DRAW_LINE                    32777
#define ID_DRAW_CIRCLE                  32778
#define ID_DRAW_ELIPESE                 32779
#define ID_DRAW_RECTANGLE               32780
#define ID_MENUITEM32781                32781
#define ID_DRAW_ROUNDRECT               32781
#define ID_DRAW_ARC                     32782
#define ID_DRAW_POLYGON                 32783
#define ID_DRAW_POLYLINE                32784
#define ID_DRAW_CONLINE                 32785
#define ID_DRAW_BEZIERLINE              32786
#define ID_TMFILE_OPEN                  32787
#define ID_TMFILE_SAVE                  32788
#define ID_DRAW_GON                     32789
#define ID_DRAW_CLEANER                 32790
#define ID_GEOMOD_TETR                  32792
#define ID_GEOMOD_HEX                   32793
#define ID_GEOMOD_OCT                   32794
#define ID_GEOMOD_DODEC                 32795
#define ID_GEOMOD_ICOS                  32796
#define ID_GEOMOD_BALL                  32797
#define ID_GEOMOD_CYLINDER              32798
#define ID_GEOMOD_CONE                  32799
#define ID_GEOMOD_TORUS                 32800
#define ID_TRANGLELIZED                 32801
#define ID_LINEMODE_BEZIER              32802
#define ID_LINEMOD_EDIT                 32803
#define ID_SCANDIS_DDALINE              32804
#define ID_SCANDIS_ANTIALIASLINE        32805
#define ID_SCAN_SEEDFILL                32806
#define ID_SCAN_TRANGLEFILL             32807
#define ID_VARYPROJ                     32808
#define ID_GRAPH_VARY                   32808
#define ID_MODHIDE_BACKREMOVE           32809
#define ID_MODHIDE_DEEPBUFF             32810
#define ID_MODLIGHT_FLAT                32811
#define ID_MODLIGHT_MATERIALEX          32812
#define ID_DRAW_NULL                    32813
#define ID_MENUITEM32814                32814
#define ID_DISMOD_POINTCLOUD            32815
#define ID_DISMOD_LINEAR                32816
#define ID_DISMOD_FLAT                  32817
#define ID_DISMOD_CLEANPAINTER          32818
#define ID_PROJ_MAINVIEW                32820
#define ID_PROJ_SIDEVIEW                32821
#define ID_PROJ_TOPVIEW                 32822
#define ID_PROJ_OBLIQUE                 32823
#define ID_PROJ_WORDTOSCREEN            32824
#define ID_PROJ_ONEPOINT                32825
#define ID_PROJ_TWOPOINT                32826
#define ID_PROJ_THREEPOINT              32827
#define ID_PROJ_DEEPSCREEN              32828
#define ID_PROJ_ORTHOGONAL              32829
#define ID_MODHIDE_NONE                 32830
#define ID_MODLIGHT_NONE                32831
#define ID_MODLIGHT_MATERIAEX           32832
#define ID_MODLIGHT_LIGHT               32833
#define ID_OPERATION_TIPS               32834
#define ID_CARTON_SETTING               32835
#define ID_DISMOD_NONE                  32836
#define ID_LINEMOD_BEZIERYSPIN          32837
#define ID_SHOW_ORGLINE                 32842
#define ID_HIDE_ORGLINE                 32843
#define ID_LINEMOD_BEZIERXSPIN          32844
#define ID_OPERATION_BASEOPE            32845
#define ID_GEOMOD_BALLEX                32846
#define ID_32847                        32847
#define ID_LINEMODE_POLYLINE            32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
